SERIES = {
    "Baldur's Gate": ("Baldur's Gate", "Baldur's Gate II: Shadows of Amn", "Baldur's Gate III"),
    "Red Dead": ('Red Dead Revolver', 'Red Dead Redemption', 'Red Dead Redemption 2'),
    'The Witcher': ('The Witcher 2: Assassin of Kings', 'The Witcher 3: Wild Hunt'),
    'Metal Gear Solid': ('Metal Gear Solid', 'Metal Gear Solid 2: Sons of Liberty', 'Metal Gear Solid 3: Snake Eater', 'METAL GEAR SOLID V: The Phantom Pain'),
    'Zelda (3D)': ('The Legend of Zelda: Ocarina of Time', "The Legend of Zelda: Majora's Mask", 'The Legend of Zelda: The Wind Waker', 'The Legend of Zelda: Twilight Princess'),
    'System Shock': ('System Shock (2023)', 'System Shock 2'),
    'Mother': ('Earthbound', 'Mother 3'),
    'Donkey Kong Country': ('Donkey Kong Country', "Donkey Kong Country 2: Diddy's Kong Quest", 'Donkey Kong Country: Tropical Freeze'),
    'Dark Forces': ('Star Wars, Dark Forces Remaster', 'Star Wars Jedi Knight: Dark Forces II', 'Star Wars Jedi Knight II - Jedi Outcast'),
    'WH40K Dawn of War': ('Warhammer 40,000: Dawn of War - Dark Crusade', 'Warhammer 40,000: Dawn of War - Soulstorm'),
    'Dishonored': ('Dishonored', 'Dishonored 2'),
    'Half-Life': ('Half-Life', 'Half-Life 2', 'Half-Life: Alyx'),
    'Mario (2d)': ('Super Mario Bros.', 'Super Mario Bros. 2', 'Super Mario Bros. 3', 'Super Mario World', "Super Mario World 2: Yoshi's Island", 'Super Mario Bros. Wonder'),
    'Persona': ('Persona 3 Reload', 'Persona 4 Golden', 'Persona 5 Royal'),
    'Psychonauts': ('Psychonauts', 'Psychonauts 2'),
    'Pillars of Eternity': ('Pillars of Eternity', 'Pillars of Eternity II: Deadfire'),
    'Hollow Knight': ('Hollow Knight', 'Hollow Knight: Silksong'),
    'Dark Souls': ('Dark Souls', 'Dark Souls II: Scholar of the First Sin', 'Dark Souls III'),
    'KOTOR': ('Star Wars: Knights of the Old Republic', 'Star Wars: Knights of the Old Republic II - The Sith Lords'),
    'Halo': ('Halo: Combat Evolved', 'Halo 2', 'Halo 3', 'Halo 3: ODST', 'Halo: Reach', 'Halo 4', 'Halo Infinite'),
    'Mass Effect': ('Mass Effect', 'Mass Effect 2', 'Mass Effect 3', 'Mass Effect Andromeda', 'Mass Effect 4'),
    'Fallout (Black Isle)': ('Fallout', 'Fallout 2'),
    'Fallout (Bethesda)': ('Fallout 3', 'Fallout 4'),
    'Lies of P': ('Lies of P', 'Lies of P: Overture'),
    'Smash Bros.': ('Super Smash Bros.', 'Super Smash Bros. Melee', 'Super Smash Bros. Brawl', 'Super Smash Bros. Ultimate'),
    'The Elder Scrolls': ('The Elder Scrolls IV: Oblivion', 'The Elder Scrolls V: Skyrim'),
    'Metroid': ('Super Metroid', 'Metroid Fusion', 'Metroid: Zero Mission', 'Metroid Dread'),
    'Metroid Prime': ('Metroid Prime', 'Metroid Prime 2: Echoes'),
    'Zelda (botw)': ('The Legend of Zelda: Breath of the Wild', 'The Legend of Zelda: Tears of the Kingdom'),
    'Banjo-Kazooie': ('Banjo-Kazooie', 'Banjo-Tooie'),
    'DOOM': ('Doom (1993)', 'DOOM II'),
    'DOOM Reboot': ('Doom (2016)', 'Doom Eternal', 'DOOM: The Dark Ages'),
    'Bioshock': ('Bioshock', 'Bioshock 2', 'Bioshock Infinite'),
    'Star Wars Jedi': ('Star Wars Jedi: Fallen Order', 'Star Wars Jedi: Survivor'),
    'Batman: Arkham': ('Batman: Arkham Asylum', 'Batman: Arkham City', 'Batman: Arkham Origins', 'Batman: Arkham Knight'),
    'Rachet & Clank': ('Ratchet & Clank', 'Ratchet & Clank: Going Commando', 'Ratchet & Clank: Up Your Arsenal', 'Ratchet: Deadlocked', 'Ratchet & Clank: Rift Apart'),
    'Pokemon': ('Pokemon Red Version', 'Pokemon Gold Version', 'Pokemon Ruby Version', 'Pokemon FireRed Version', 'Pokemon Emerald Version', 'Pokemon Diamond Version', 'Pokemon SoulSilver Version', 'Pokemon White Version', 'Pokemon Black Version 2', 'Pokemon X', 'Pokemon Omega Ruby', 'Pokemon Sun', 'Pokemon Brilliant Diamond', 'Pokemon Shield', 'Pokemon Violet'),
    'Pokemon Legends': ('Pokemon Legends: Arceus', 'Pokemon Legends: Z-A'),
    'Pokemon Snap': ('Pokemon Snap', 'New Pokemon Snap'),
    'God of War (reboot)': ('God of War', 'God of War: Ragnarok'),
    'Fire Emblem': ('Fire Emblem: The Binding Blade', 'Fire Emblem: The Blazing Blade', 'Fire Emblem: The Sacred Stones', 'Fire Emblem: Path of Radiance', 'Fire Emblem: Radiant Dawn', 'Fire Emblem: Shadow Dragon', 'Fire Emblem Awakening', 'Fire Emblem Fates: Birthright', 'Fire Emblem Fates: Conquest', 'Fire Emblem Fates: Revelation', 'Fire Emblem Echoes: Shadows of Valentia', 'Fire Emblem: Three Houses', 'Fire Emblem Engage', "Fire Emblem: Fortune's Weave"),
    'Borderlands': ('Borderlands', 'Borderlands 2', 'Borderlands 3', 'Borderlands 4'),
    'Ass Creed': ("Assassin's Creed", "Assassin's Creed II", "Assassin's Creed Brotherhood", "Assassin's Creed III", "Assassin's Creed IV: Black Flag"),
    'FSN': ('Fate/Stay Night Remastered', 'Fate/Hollow Ataraxia'),
    'THPS': ("Tony Hawk's Pro Skater", "Tony Hawk's Pro Skater 2", "Tony Hawk's Pro Skater 3", "Tony Hawk's Pro Skater 4", "Tony Hawk's Underground", "Tony Hawk's Pro Skater 1+2", "Tony Hawk's Pro Skater 3+4"),
    'Civ': ("Sid Meier's Civilization", "Sid Meier's Civilization II", "Sid Meier's Civilization III", "Sid Meier's Civilization IV", "Sid Meier's Civilization V", "Sid Meier's Civilization VI", "Sid Meier's Civilization VII"),
    'Spider-Man': ("Marvel's Spider-Man Remastered", "Marvel's Spider-Man: Miles Morales", "Marvel's Spider-Man 2"),
    "Dragon's Dogma": ("Dragon's Dogma: Dark Arisen", "Dragon's Dogma 2"),
    'Gears of War': ("Gears of War", "Gears of War 2", "Gears of War 3"),
    'Guitar Hero': ('Guitar Hero II', 'Guitar Hero III: Legends of Rock'),
    'Rock Band': ('Rock Band', 'Rock Band 2'),
    'Animal Crossing': ('Animal Crossing', 'Animal Crossing: New Horizons'),
    'SoulCalibur': ('Soul Edge', 'SoulCalibur', 'SoulCalibur II', 'SoulCalibur III', 'SoulCalibur IV'),
    'Skate': ('Skate', 'Skate 2'),
    'CoD': ('Call of Duty', 'Call of Duty 2', 'Call of Duty 3: World at War', 'Call of Duty 4: Modern Warfare', 'Call of Duty: Modern Warfare 2', 'Call of Duty: Black Ops'),
    'The Show': tuple(['MLB 09: The Show'] + [f'MLB {n}: The Show' for n in range(10, 25)]),
    'Mario Kart': ('Mario Kart 64', 'Mario Kart: Double Dash', 'Mario Kart DS', 'Mario Kart 8 Deluxe', 'Mario Kart World'),
    'Mario (3D)': ('Super Mario 64', 'Super Mario Sunshine', 'Super Mario Galaxy', 'Super Mario Galaxy 2', 'Super Mario Odyssey'),
    'Burnout': ("Burnout 3: Takedown", 'Burnout Revenge', 'Burnout Paradise'),
    'Nep': ('Hyperdimension Neptunia Re;Birth1', 'Hyperdimension Neptunia Re;Birth2: Sisters Generation', 'Hyperdimension Neptunia Re;Birth3: V Generation', 'Megadimension Neptunia VII'),
    'Dragon Age': ('Dragon Age: Origins', 'Dragon Age II', 'Dragon Age: Inquisition', 'Dragon Age: The Veilguard'),
    'NCAA': tuple([f'NCAA Football 0{n}' for n in range(1,10)] + [f'NCAA Football {n}' for n in range(10,12)]),
    'PGR': tuple(['Project Gotham Racing'] + [f'Project Gotham Racing {n}' for n in range(2, 5)]),
    'Star Wars: Battlefront': ('Star Wars: Battlefront', 'Star Wars: Battlefront 2'),
    'Madden': ([f'Madden NFL 0{n}' for n in range(1, 10)] + [f'Madden NFL {n}' for n in range(10, 27)]),
}